bounswe/bounswe2024group6

- frontend/components.json
- frontend/package.json
- frontend/postcss.config.js
- frontend/src/App.tsx
- frontend/src/components/ui/button.tsx
- frontend/src/index.css
- frontend/src/lib/utils.ts
- frontend/tailwind.config.js
- frontend/tsconfig.json
- frontend/vite.config.ts
Added component library for front-end. Can you merge please?
> feat(frontend): set up shadcn/ui component library

- backend/django-rest-auth/requirements.txt
- backend/django-rest-auth/server/utils.py
- backend/django-rest-auth/server/views.py
WikiData API calls are asynchronous now and the process is sped up by almost 300%!
> improvement(backend): async WD API calls

- docker-compose.yml
- new_backend/project/Dockerfile
- new_backend/project/project/settings.py
- new_backend/project/requirements.txt
This PR:
- Fixes CORS errors
- Sets up MySQL connection
- Adds backend Dockerfile and requirements
> fix(backend, devops): setup mysql connection, resolve CORS errors

- frontend/src/components/Navbar.tsx
- frontend/src/hooks/useAuth.tsx
- frontend/src/main.tsx
- frontend/src/pages/Profile.tsx
This PR adds:
- getToken, getUsername actions in useAuth hook
- dynamic routing for profiles
- basic profile ui for testing
> feat(frontend): add getToken, getUsername actions, add basic profile ui, add dynamic profile routes

- new_backend/project/app/views.py
added user profile to show bookmarked, liked, commented, and sensed posts.
> added user-profile

- frontend/Dockerfile
- frontend/package.json
- frontend/src/components/ui/dialog.tsx
- frontend/src/components/ui/textarea.tsx
- frontend/src/pages/Profile.tsx
This PR:
- Introduces a frontend Dockerfile fix
- Adds an edit profile component
> fea(frontend): add edit profile modal, fix Dockerfile

- new_backend/project/app/utils.py
Sped up the building endpoint to retrieve all information with a single query and increased the quantity of information retrieved about architects (the ones with non-preferred ranks show up too now).
> improvement: sped up and broadened the building query

- new_backend/project/app/tests.py
- new_backend/project/app/urls.py
- new_backend/project/app/views.py
- new_backend/project/project/settings.py
Testing comment and endpoint of delete comment
> delete comment and comment tests

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/common/index.tsx
- frontend/src/components/common/navbar.tsx
- frontend/src/pages/browse.tsx
- frontend/src/pages/forum.tsx
- frontend/src/pages/post.tsx
- frontend/src/pages/profile.tsx
- frontend/src/pages/quiz.tsx
- frontend/src/pages/quizzes.tsx
> FRONTEND-309: Create Navbar

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/common/navbar.tsx
- frontend/src/main.tsx
- frontend/tailwind.config.js
> FRONTEND-311: Switch to NextUI

- frontend/src/components/common/navbar.tsx
- frontend/src/components/post/index.tsx
- frontend/src/components/post/post-card-skeleton.tsx
- frontend/src/components/post/post-card.tsx
- frontend/src/pages/forum.tsx
> feat(frontend): create post component

- frontend/src/components/post/post-card-skeleton.tsx
- frontend/src/components/post/post-card.tsx
- frontend/src/pages/forum.tsx
[issue319](https://github.com/bounswe/bounswe2024group6/issues/319)
Other than making all the card clickable, I did all of them.
Making the card clickable blocks many other functionalities.
This is the final look:
> FRONTEND-319: Finalise Post Component Design

- frontend/src/components/post/post-card.tsx
- frontend/src/pages/forum.tsx
- frontend/src/pages/post.tsx
> feat(frontend): create post page

- mobile/searchitect/app/_layout.tsx
- mobile/searchitect/app/register.tsx
- mobile/searchitect/app/signUp.tsx
- mobile/searchitect/package-lock.json
- mobile/searchitect/package.json
Fixes [331](https://github.com/bounswe/bounswe2024group6/issues/331).
I've implemented a signup page with client side checks. It's been implemented in accordance with the mobile mockups. 
Navbar will be fixed once navbar PR is merged.
> MOBILE-331: Create a SignUp Page

- frontend/src/components/post/compose-post-button.tsx
- frontend/src/components/post/compose-post-form.tsx
- frontend/src/components/post/index.tsx
- frontend/src/main.tsx
- frontend/src/pages/compose-post.tsx
- frontend/src/pages/forum.tsx
- frontend/src/pages/index.tsx
I created a button to link to the post creation page and the creation page itself.
> feat(frontend): create post creation template

- frontend/src/components/post/compose-post-form.tsx
Added Preview functionality for post creation page
> feat(frontend): added preview for post creation

- backend/app/urls.py
- docker-compose.yml
- frontend/Dockerfile
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/post/compose-post-button.tsx
- frontend/src/lib/baseURL.ts
- frontend/src/pages/forum.tsx
> feat(frontend): dockerize frontend and connect to backend

- backend/app/apps.py
- backend/app/views.py
> fix(backend): Fix Mock Data Creation

- mobile/searchitect/app/index.tsx
- mobile/searchitect/app/quizCreationInfo.tsx
- mobile/searchitect/app/quizCreationQuestionList.tsx
- mobile/searchitect/app/quizCreationSettings.tsx
Quiz creation process consists of 3 pages, you can find their implementations under different commits.
> feat(mobile): quiz creation page

- frontend/src/components/common/navbar.tsx
[issue](https://github.com/bounswe/bounswe2024group6/issues/385)
> feat(frontend): adjusted navbar design

- frontend/src/components/post/compose-post-button.tsx
- frontend/src/pages/forum.tsx
[issue382](https://github.com/bounswe/bounswe2024group6/issues/382)
> feat(frontend): added filtering view above forum posts

- frontend/src/components/common/navbar.tsx
[issue](https://github.com/bounswe/bounswe2024group6/issues/387)
> feat(frontend): adjusted avatar in the navbar

- frontend/Dockerfile
> fix(frontend): update dockerfile

- mobile/searchitect/app/quizCreationInfo.tsx
- mobile/searchitect/app/quizCreationSettings.tsx
Fixes #375.
This PR introduces several enhancements and refinements to the quiz creation workflow, specifically focusing on the QuizCreationSettings and QuizCreationInfo pages. The following changes have been made:
A feature has been implemented to allow users to select a correct answer before proceeding, ensuring that quizzes are created with valid answers.
Added a margin at the top of both the QuizCreationSettings and QuizCreationInfo pages to ensure the navbar is not too close to the top of the screen.
The question prompt is now editable, moving away from the static implementation.
The question prompt has been enclosed in a visually distinct yellow container for improved clarity.
The 'Add Question' button is now only pressable when all answers are provided, unique, the correct answer …
> feat+refactor(mobile): Quiz Creation Flow - QuizCreationSettings and QuizCreationInfo Pages

- frontend/src/pages/post.tsx
- frontend/src/types.ts
> feat(frontend): connect post page with backend

- frontend/src/pages/forum.tsx
> feat(frontend): connect forum with backend

- frontend/src/pages/profile.tsx
- frontend/src/types.ts
> feat(frontend): connect profile page with backend

- mobile/searchitect/app/quizCreationSettings.tsx
Fixes #386.
This PR introduces several important updates and refinements to the quiz creation functionality within the mobile application. The following changes have been implemented:
A new field for quiz descriptions has been added, allowing users to provide additional context for their quizzes.
The audience selection feature has been removed.
The 'Add Question' button is now disabled if required inputs (answers, quiz title, and description) are not provided, preventing incomplete submissions.
Added padding throughout the quiz creation pages to improve layout and visual appeal.
Replaced all Pressable components with TouchableOpacity for improved touch responsiveness and consistency across the application.
These enhancements aim to improve the user experience during quiz creation by …
> feat+refactor(mobile): New Version of Quiz Creations

- frontend/src/pages/profile.tsx
[issue](https://github.com/bounswe/bounswe2024group6/issues/411)
> fix(frontend): fixed profile page design

- frontend/src/components/common/navbar.tsx
- frontend/src/components/post/compose-post-button.tsx
- frontend/src/components/post/post-card.tsx
replaced Link components and anchor tags with navigate… functionality
> fix(frontend): HOT FIX

- mobile/searchitect/app/quizCreationInfo.tsx
- mobile/searchitect/app/quizCreationQuestionList.tsx
- mobile/searchitect/app/quizCreationSettings.tsx
- mobile/searchitect/app/quizFeed.tsx
Fixes #377.
This PR introduces crucial enhancements to the routing and temporary storage functionality within the quiz creation. The following features have been implemented:
Added routing capabilities for the quiz feed, improving navigation throughout the app.
Implemented routing for the QuizCreationSettings page when the 'Add Questions' button is pressed.
Introduced a temporary storage feature for quiz questions, allowing users to save their progress while creating quizzes.
> feat(mobile): Quiz Creation Flow - Navigation Across Quiz Creation Flow Pages - Temporary Quiz Data Storage

- mobile/searchitect/app/_layout.tsx
- mobile/searchitect/app/quizQuestion.tsx
- mobile/searchitect/app/quizResults.tsx
Fixes #412.
This PR includes the following changes: 
- quizQuestion page header was removed.
- A mockQuiz was added to the quizQuestion page.
- QuizQuestionProps and QuizQuestion types were created.
- New state variables have been added to keep track of which answer was chosen for which question.
- The buttons in the quizQuestion page now navigate to the appropriate page and perform the correct actions.
- Navigation between quiz questions now possible.
- The 'Previous' button is now grayed out and disabled when at the first question of a quiz.
- The 'Next' button is replaced with 'Finish' button at the last question of a quiz.
- A function for score calculation was added.
- When a quiz is finished, it now routes to the quiz result page with the appropriate data.
- The new like button …
> feat(mobile): Interactive Quiz Page using Mock Data

- mobile/searchitect/app/_layout.tsx
- mobile/searchitect/app/navbar.tsx
- mobile/searchitect/app/quizCreationInfo.tsx
- mobile/searchitect/app/quizDetails.tsx
- mobile/searchitect/app/quizQuestion.tsx
- mobile/searchitect/app/quizResults.tsx
- mobile/searchitect/package-lock.json
Fixes #421. 
This issue includes a variety of changes, including:
* Changes to the default values of the created and solved quizzes.
* Removal of headers from some pages
* Adding onPress functions to some buttons.
> fix(mobile): Final Fixes before prerelease

- mobile/bulingo/app/login.tsx
- mobile/bulingo/app/register.tsx
These functions made api calls to http endpoints, which causes the apk to break, so they were removed until we can find a reliable fix. Fixes #424.
> fix(mobile): Remove fetch function from Login and Register

- mobile/bulingo/app/index.tsx
- mobile/bulingo/app/login.tsx
- mobile/bulingo/app/register.tsx
Since the register page doesn't work, it has been disabled and also colored gray. This PR fixes #426.
> fix(mobile): Disable register Buttons

- README.md
Build instructions for mobile is added to the readme.
> Add mobile build instructions

- frontend/src/components/common/navbar.tsx
- frontend/src/pages/profile.tsx
[issue](https://github.com/bounswe/bounswe2024group6/issues/453)
> feat(frontend): reorganised profile page and added options to profile icon in navbar

- backend/app/models.py
- backend/app/serializers.py
- backend/app/urls.py
- backend/app/views_directory/comments.py
- backend/app/views_directory/postviews.py
I have implemented it and updated the like count of the posts accordingly can you merge it
> Like Post and Unlike Post functionality added

- backend/app/models.py
Activity streams model has been added also activity streams saving functionalities for the following functions has been added.
comment,
like comment,
like post,
follow
@kaanyolcu22 can you check and approve
> activity_streams_model

- frontend/src/components/common/navbar.tsx
- frontend/src/components/post/compose-post-button.tsx
- frontend/src/components/post/create-quiz-button.tsx
- frontend/src/components/post/post-card.tsx
- frontend/src/components/quiz/create-quiz-metadata.tsx
- frontend/src/components/quiz/create-quiz-question.tsx
- frontend/src/lib/baseURL.ts
- frontend/src/main.tsx
- frontend/src/pages/forum.tsx
- frontend/src/pages/quiz-creation.tsx
- frontend/src/pages/quizzes.tsx
> feat(frontend): create quiz creation page

- frontend/src/pages/quiz-details.tsx
[issue](https://github.com/bounswe/bounswe2024group6/issues/528)
> feat(frontend): added photo feature to quiz details page

- frontend/src/components/common/navbar.tsx
[issue](https://github.com/bounswe/bounswe2024group6/issues/540)
> Fix(frontend): Fixed the background issue with the profile avatar

- frontend/src/components/common/utils.tsx
- frontend/src/pages/forum.tsx
- frontend/src/types.ts
[issue](https://github.com/bounswe/bounswe2024group6/issues/547)
> feat(frontend): implemented forum sorting methods

- frontend/src/components/post/compose-post-form.tsx
- frontend/src/pages/profile.tsx
Added sorting for profile too and fixed difficulty tag issue
> feat(frontend): sorted posts in profile and fixed difficulty tag issue

- backend/app/views_directory/postviews.py
now, bookmark seen on like, unlike
> like_unlike problem solution

- frontend/src/components/common/utils.tsx
- frontend/src/components/post/compose-post-form.tsx
- frontend/src/components/post/post-card.tsx
- frontend/src/pages/forum.tsx
- frontend/src/types.ts
Added liking functionality, and edited forum view
> Frontend 536

- frontend/src/components/post/compose-post-form.tsx
- frontend/src/pages/forum.tsx
[issue](https://github.com/bounswe/bounswe2024group6/issues/551)
> feat(frontend): Added filtering functionality to forum

- frontend/package-lock.json
- frontend/package.json
- frontend/public/mockServiceWorker.js
- frontend/src/mocks/handlers.ts
- frontend/src/mocks/node.ts
- frontend/src/pages/forum.test.tsx
- frontend/tsconfig.app.json
- frontend/tsconfig.json
- frontend/tsconfig.node.json
- frontend/vitest.config.ts
- frontend/vitest.setup.ts
> feat(frontend): create testing environment

- frontend/src/components/auth/login.tsx
- frontend/src/components/common/navbar.tsx
- frontend/src/components/common/user-card.tsx
- frontend/src/components/post/post-card.tsx
- frontend/src/pages/profile.tsx
[issue](https://github.com/bounswe/bounswe2024group6/issues/559)
> feat(frontend): implemented other/own users' profile views

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/common/navbar.tsx
- frontend/src/components/post/post-card-skeleton.tsx
- frontend/src/components/post/post-card.tsx
- frontend/src/mocks/handlers.ts
- frontend/src/pages/forum.test.tsx
- frontend/vitest.config.ts
- frontend/vitest.setup.ts
> feat(frontend): add forum page tests

- frontend/src/components/common/utils.tsx
- frontend/src/components/post/compose-post-form.tsx
- frontend/src/components/post/post-card.tsx
- frontend/src/pages/forum.tsx
- frontend/src/pages/post.tsx
- frontend/src/pages/profile.tsx
- frontend/src/types.ts
> feat(frontend): persist is_liked information on refresh

- frontend/src/components/post/post-card.tsx
> feat(frontend): implement unlike functionality

- frontend/src/components/common/utils.tsx
- frontend/src/components/post/compose-post-form.tsx
- frontend/src/components/post/post-card.tsx
- frontend/src/pages/forum.tsx
- frontend/src/pages/post.tsx
- frontend/src/pages/profile.tsx
- frontend/src/types.ts
> feat(frontend): connect bookmark functionality to backend

- mobile/bulingo/app/TokenManager.ts
- mobile/bulingo/app/login.tsx
- mobile/bulingo/app/register.tsx
Fixes #531
This PR includes the following changes:
* The TokenManager singleton class has been expanded and refactored, it now has an authenticatedFetchFunction that uses the access token, and it is able to better manage access/refresh tokens. 
* The url's and the response handling logic in the login and register pages have been changed to fit the new backend deployment. (Found in BACKEND-DEV branch as of now).
> feat(mobile): Refactor TokenManager

- mobile/bulingo/app/(tabs)/index.tsx
- mobile/bulingo/app/(tabs)/quizzes/index.tsx
- mobile/bulingo/app/login.tsx
- mobile/bulingo/package-lock.json
- mobile/bulingo/package.json
- package-lock.json
Fixes #599.
- API endpoint integration for fetching quizzes is completed.
- Fetched quizzes are formatted and displayed on UI.
- Error handling is available for possible error cases. 
- I've tested the changes manually.
> feat(mobile): Connect Quiz Feed to Backend

- frontend/src/components/common/utils.tsx
- frontend/src/pages/profile.tsx
- frontend/src/types.ts
> feat(frontend): implement follow/unfollow functionality

- mobile/bulingo/app/(tabs)/quizzes/quizCreationInfo.tsx
Fixes #565.
- Unique key error on Quiz Creation Info Page is fixed.
> fix(mobile): fix unique key error on Quiz Creation Info

- frontend/src/components/notification/notification-card.tsx
- frontend/src/components/quiz/quiz-card.tsx
- frontend/src/lib/baseURL.ts
- frontend/src/pages/notifications.tsx
- frontend/src/pages/profile.tsx
> feat(frontend): implement notifications functionality

- frontend/src/components/common/utils.tsx
- frontend/src/pages/forum.tsx
- frontend/src/pages/post.tsx
- frontend/src/types.ts
> feat(frontend): implement comments section of the posts

- frontend/src/components/auth/login.tsx
- frontend/src/components/auth/register.tsx
- frontend/src/pages/home.tsx
Autofilling breaks the login register logic, which need to be fixed
> fix(frontend): Enhancements made in login-register pages

- mobile/bulingo/app/(tabs)/quizzes/index.tsx
- mobile/bulingo/app/(tabs)/quizzes/quizDetails.tsx
- mobile/bulingo/app/TokenManager.ts
- mobile/bulingo/app/login.tsx
- mobile/bulingo/app/register.tsx
Fixes #620.
- The quiz ID is passed to the Quiz Details page when a feed item is clicked.
- Quiz details are fetched using the passed ID on the Quiz Details page.
- The quiz details are properly formatted and displayed to the user.
- Error handling and loading components are created and integrated.
- The Quiz Details page is slightly modified to include a loading screen and error handling. Additionally, some components are refactored for an improved UI.
> feat(mobile): Connect Quiz Details to the Backend

- frontend/src/components/common/user-card.tsx
- frontend/src/components/post/post-card.tsx
- frontend/src/pages/profile.tsx
[issue](https://github.com/bounswe/bounswe2024group6/issues/539) and fixed missing usernames in profile posts section.
> feat(frontend): implemented popover user cards

- frontend/src/components/post/post-card-skeleton.tsx
- frontend/src/pages/forum.tsx
- frontend/src/pages/post.tsx
- frontend/src/pages/profile.tsx
A skeleton need to be shown while waiting for data fetching
> feat(frontend): Skeletons Added to Profile, Forum and Comments sections

- frontend/src/components/common/navbar.tsx
Currently, the logo navigates to login page and does not display clickable property, it needs to be fixed
> fix(frontend): fixed Logo behavior

- frontend/src/components/post/comment-skeleton.tsx
- frontend/src/pages/forum.tsx
- frontend/src/pages/post.tsx
Little enhancements for a better UI, regarding Adjust the Skeletons and the Display of the Comments Page
> fix(frontend): fixed the view of comments and forum

- frontend/src/components/common/user-card.tsx
- frontend/src/pages/profile.tsx
[issue](https://github.com/bounswe/bounswe2024group6/issues/644)
> fix(frontend): displayed correct follower count on related places

- mobile/bulingo/app/(tabs)/quizzes/quizCreationInfo.tsx
- mobile/bulingo/app/(tabs)/quizzes/quizCreationQuestionList.tsx
- mobile/bulingo/app/(tabs)/quizzes/quizDetails.tsx
- mobile/bulingo/app/(tabs)/quizzes/quizQuestion.tsx
- mobile/bulingo/app/(tabs)/quizzes/quizResults.tsx
Fixes #624 and #656.
-  Integrate the /quiz/start/ endpoint to fetch and initialise quiz progress. 
- Implement the /quiz/question/solve/ endpoint to submit answers for each question.
- Connect the /quiz/submit/ endpoint to finalise the quiz.
- Ensured seamless interaction with the backend by implementing robust error handling and testing all functionalities thoroughly.
- Displayed questions on the UI.
- Connect Quiz Results to the backend.
- Random quiz recommendation is added.
> feat(mobile): Integrating Quiz Solution Logic with Backend

- frontend/src/lib/baseURL.ts
- mobile/bulingo/app/(tabs)/quizzes/index.tsx
- mobile/bulingo/app/(tabs)/quizzes/quizDetails.tsx
- mobile/bulingo/app/(tabs)/quizzes/quizResults.tsx
- mobile/bulingo/app/(tabs)/quizzes/quizReview.tsx
- mobile/bulingo/app/TokenManager.ts
- mobile/bulingo/app/login.tsx
- mobile/bulingo/app/register.tsx
Fixes #660.
- Review button is added to the quiz results page. 
- Review page is added for users to review their mistakes.
> feat(mobile): Review Solved Quizzes

- mobile/bulingo/app/(tabs)/index.tsx
- mobile/bulingo/app/(tabs)/notifications.tsx
- mobile/bulingo/app/(tabs)/profile/bookmarkedPostsAndComments.tsx
- mobile/bulingo/app/(tabs)/profile/bookmarkedQuizzes.tsx
- mobile/bulingo/app/(tabs)/profile/editProfile.tsx
- mobile/bulingo/app/(tabs)/profile/followers.tsx
- mobile/bulingo/app/(tabs)/profile/following.tsx
- mobile/bulingo/app/(tabs)/profile/index.tsx
- mobile/bulingo/app/(tabs)/profile/likedQuizzes.tsx
- mobile/bulingo/app/(tabs)/profile/userCard.tsx
- mobile/bulingo/app/(tabs)/profile/users/[username].tsx
- mobile/bulingo/app/(tabs)/profile/users/[username]/followers.tsx
- mobile/bulingo/app/(tabs)/profile/users/[username]/following.tsx
- mobile/bulingo/app/(tabs)/profile/users/[username]/index.tsx
- mobile/bulingo/app/(tabs)/quizzes/index.tsx
- mobile/bulingo/app/TokenManager.ts
- mobile/bulingo/app/components/topNotification.tsx
- mobile/bulingo/app/login.tsx
- mobile/bulingo/app/register.tsx
- mobile/bulingo/package-lock.json
Fixes #646.
This PR includes the commits from #640 because it relies on the same components. Therefore, PR #640 SHOULD BE MERGED BEFORE THIS PR IS MERGED.
This PR adds a small notification that disappears after 3 seconds. The notification is present on the home page after a successful login or registration. The notification is also present in the login page if incorrect login information is provided.
> feat(mobile): Notifications on successful login/register

- frontend/src/components/auth/login.tsx
- frontend/src/components/auth/register.tsx
- frontend/src/components/post/post-card.tsx
- frontend/src/components/quiz/quiz-card.tsx
- frontend/src/pages/home.tsx
- frontend/src/pages/post.tsx
Just double-checked everything. Fixed small details.
> feat(frontend): last touches

- frontend/package.json
- frontend/src/components/post/compose-post-button.tsx
- frontend/src/components/post/compose-post-form.tsx
- frontend/src/lib/baseURL.ts
- frontend/src/pages/forum.test.tsx
- frontend/src/pages/forum.tsx
- frontend/src/pages/forumCompose.test.tsx
- frontend/src/pages/profile-update.tsx
- frontend/src/pages/profile.tsx
Compose Post Functionality need to be tested to see if it works as expected
> Frontend 680

- mobile/bulingo/app/(tabs)/index.tsx
- mobile/bulingo/app/(tabs)/quizzes/quizCreationInfo.tsx
- mobile/bulingo/app/(tabs)/quizzes/quizCreationQuestionList.tsx
- mobile/bulingo/app/(tabs)/quizzes/quizCreationSettings.tsx
- mobile/bulingo/app/(tabs)/quizzes/quizDetails.tsx
- mobile/bulingo/app/(tabs)/quizzes/quizQuestion.tsx
- mobile/bulingo/app/(tabs)/quizzes/quizResults.tsx
- mobile/bulingo/app/(tabs)/quizzes/quizReview.tsx
- mobile/bulingo/package-lock.json
- mobile/bulingo/package.json
Fixes #670.
- The Shadow library caused a bug that stopped the app, so I have removed it.
- I have removed the shadow components.
- I have redesigned the buttons.
- I have built an APK and tested it.
> refactor(mobile): remove shadows + redesign buttons

- mobile/bulingo/app/(tabs)/quizzes/quizCreationInfo.tsx
- mobile/bulingo/app/(tabs)/quizzes/quizResults.tsx
Fixes #702.
- Quizzes are recommended to users based on the solved quiz level and tags.
- The existing backend endpoint is utilised for this functionality. @arastasci 
- A message indicating "No Recommendation" is displayed if no quizzes are available.
- This PR also includes a minor refactor of the quiz creation process by removing the default title.
> feat(mobile): Quiz Recommendation According to Solved Quiz Level

- mobile/bulingo/app/(tabs)/quizzes/index.tsx
- mobile/bulingo/app/TokenManager.ts
- mobile/bulingo/app/login.tsx
- mobile/bulingo/app/register.tsx
- mobile/bulingo/package-lock.json
This is a simple change and the title is self-explanatory.
> chore(mobile): change base url to digital ocean deployment

- frontend/src/components/common/utils.tsx
- frontend/src/components/quiz/quiz-card.tsx
- frontend/src/pages/quizzes.tsx
- frontend/src/types.ts
connected quiz forum with backend
> feat(frontend): connected quiz forum with backend

- mobile/bulingo/app/(tabs)/quizzes/quizCreationInfo.tsx
Fixes #743.
- When users type a word in the question section and click the newly added 'New Suggestion!' button:
- If type-1 is selected: it returns the Turkish translation of the English word.
- If type-2 is selected: it returns the English translation of the Turkish word.
- If type-3 is selected: it returns the meaning of the English word.
- For type-3, if more than one meaning is available, it cycles through the meanings each time the 'New Suggestion!' button is clicked.
- If none of the above are available, the "Add Answer" section remains empty, and an error message is displayed indicating that the meaning is not available.
- Additionally, answers in quiz creation are now scrollable, allowing users to scroll through and read large answers.
- I have tested the functionality on an …
> feat(mobile): Integrate Quiz Creation with Suggestion System Using Lexvo

- frontend/src/pages/profile.tsx
[issue](https://github.com/bounswe/bounswe2024group6/issues/765)
> Frontend 765: added created and solved quizzes to profile page

- backend/app/serializers.py
- backend/app/views_directory/quiz_views.py
> feat(backend): Finalize guest-quiz requirements.

- backend/app/urls.py
- backend/app/views_directory/quiz_views.py
> feat(backend): implement quiz canceling

- backend/app/views_directory/postviews.py
> impr: remove auth for post details.

- backend/app/urls.py
- backend/app/views_directory/admin_views.py
> feat(backend): admins now have banhammers

- mobile/bulingo/app/(tabs)/profile/bookmarkedWords.tsx
- mobile/bulingo/app/(tabs)/profile/following.tsx
- mobile/bulingo/app/(tabs)/profile/likedPostsAndComments.tsx
- mobile/bulingo/app/(tabs)/quizzes/index.tsx
- mobile/bulingo/app/TokenManager.ts
- mobile/bulingo/app/components/modalDictionary.tsx
- mobile/bulingo/app/login.tsx
- mobile/bulingo/app/pressableText.tsx
- mobile/bulingo/app/register.tsx
- mobile/bulingo/tsconfig.json
Fixes #773.
This PR makes the bookmark button found in the ModalDictionary component functional. It is connected to the backend and sends the appropriate request based on its state (pressed / not pressed). 
This PR also connects the Bookmarked Words page in the profile tab fetch real data from the backend. It has been tested and both bookmarking and unbookmarking work well.
> Bookmarking Words Connection to Backend (Mobile)

- frontend/src/components/post/post-card.tsx
- frontend/src/components/quiz/navigation.tsx
- frontend/src/components/quiz/question-card.tsx
- frontend/src/components/quiz/quiz-card.tsx
- frontend/src/main.tsx
- frontend/src/pages/quiz-end.tsx
- frontend/src/pages/quiz-review.tsx
- frontend/src/pages/quiz.tsx
[issue](https://github.com/bounswe/bounswe2024group6/issues/793)
> Frontend 793: added quiz review functionality

- frontend/src/components/common/navbar.tsx
- frontend/src/lib/baseURL.ts
- frontend/src/pages/browse.tsx
This PR implements the following:
> feat(frontend): implement search

- frontend/src/components/quiz/quiz-card.tsx
- frontend/src/pages/quiz-end.tsx
- frontend/src/pages/quizzes.tsx
[issue](https://github.com/bounswe/bounswe2024group6/issues/798)
> feat(frontend): added quiz recommendation feature

- frontend/src/components/auth/guest-auth-modal.tsx
- frontend/src/components/auth/login.tsx
- frontend/src/components/auth/protect-routes.tsx
- frontend/src/components/auth/register.tsx
- frontend/src/components/common/navbar.tsx
- frontend/src/components/common/user-card.tsx
- frontend/src/components/post/compose-post-button.tsx
- frontend/src/components/post/create-quiz-button.tsx
- frontend/src/components/post/post-card.tsx
- frontend/src/components/quiz/quiz-card.tsx
- frontend/src/main.tsx
- frontend/src/pages/profile.tsx
> feat(frontend): complete guest view

- frontend/src/components/common/clickable-text.tsx
- frontend/src/components/common/dictionary-modal.tsx
- frontend/src/components/post/post-card.tsx
- frontend/src/components/quiz/question-card.tsx
- frontend/src/pages/quiz-review.tsx
> feat(frontend): implement dictionary

- backend/app/views_directory/comments.py
> fix(backend): comments are viewable by anyone

- backend/app/views_directory/feed_views.py
> fix(backend): check authentication in user post feed

- frontend/src/components/common/dictionary-modal.tsx
- frontend/src/pages/profile.tsx
> feat(frontend): implement bookmark word functionality

- mobile/bulingo/app/(tabs)/profile/following.tsx
- mobile/bulingo/app/(tabs)/profile/likedPostsAndComments.tsx
- mobile/bulingo/app/(tabs)/profile/userCard.tsx
- mobile/bulingo/app/(tabs)/quizzes/index.tsx
- mobile/bulingo/app/(tabs)/search.tsx
- mobile/bulingo/app/TokenManager.ts
- mobile/bulingo/app/login.tsx
- mobile/bulingo/app/register.tsx
Fixes #663.
This PR includes a small change to the design of the search page and also connects it to the backend. Notable changes in this PR are the following:
* The search page design has been changed, and the options to sort and filter by tags have been removed.
* The option to filter by content type has been changed to allow search for only a single type of content. Its design has been slightly altered to fill the space that the other two options mentioned above filled.
* The IP has been changed with the BACKEND-DEV deployment IP. (this is a trivial change)
* The placeholders for postcard and comment card have been removed and replaced with the real components.
* The search page has been connected to the backend's 'search/' endpoint, and the results have been transformed so that they …
> Search Page Backend Connection (Mobile)

- backend/app/views_directory/quiz_views.py
> feat(backend): Add Unfinished Progress Label to Quiz Details

- frontend/src/main.tsx
- frontend/src/pages/forum.tsx
- frontend/src/pages/post.tsx
- frontend/src/pages/profile.tsx
- frontend/src/pages/quiz-details.tsx
- frontend/src/pages/quizzes.tsx
- fixed issues related to access token/guest
- added options for likes quizzes/posts
> Frontend 819: fixed issues related to access token/guest

- mobile/bulingo/app/(tabs)/quizzes/quizCreationQuestionList.tsx
Fixes #829.
- This PR updates quiz creation integration on mobile to align with the changes on the backend. 
- The logic is the same but request is now in form data type.
> refactor(mobile): update quiz creation integration

- backend/app/urls.py
- backend/app/views_directory/admin_views.py
> feat(backend): Check if the Current User is Admin

- mobile/bulingo/app/(tabs)/index.tsx
- mobile/bulingo/app/(tabs)/profile/editProfile.tsx
- mobile/bulingo/app/(tabs)/profile/followers.tsx
- mobile/bulingo/app/(tabs)/profile/following.tsx
- mobile/bulingo/app/(tabs)/profile/index.tsx
- mobile/bulingo/app/(tabs)/profile/userCard.tsx
- mobile/bulingo/app/(tabs)/profile/users/[username]/followers.tsx
- mobile/bulingo/app/(tabs)/profile/users/[username]/following.tsx
- mobile/bulingo/app/(tabs)/profile/users/[username]/index.tsx
Fixes #807.
The main change included in this PR is the ability to actually upload pictures to the backend and then display the profile pictures returned from the backend. While I was working on this, I encountered a few minor bugs related to the followers/following pages of other user profiles, so I also handled them in this PR. With the changes made in this PR, wherever a user card can be found, except in the search page. This is due to the backend not actually returning the profile picture url when performing a search for users. Once that issue is fixed, I will add the profile pictures to the mobile search page as well. However, even though I can't test it, I am pretty sure that the UserCard component will display the profile picture correctly once it is returned correctly from the …
> Profile Picture Editing & Display in Mobile

- frontend/src/pages/profile.tsx
[issue](https://github.com/bounswe/bounswe2024group6/issues/819)
> feat(frontend): added liked quizzes to profile

- mobile/bulingo/app/(tabs)/quizzes/quizResults.tsx
Fixes #839.
- This PR updates quiz result integration on mobile to align with the changes on the backend.
- The logic is the same but response fields are now updated.
> refactor(mobile): update quiz result integration

- frontend/src/components/quiz/create-quiz-question.tsx
While creating quiz questions, options should be provided to the creator on will.
> feat(frontend): recommend options while creating the quiz questins

- frontend/src/components/quiz/question-card.tsx
- frontend/src/pages/quiz-end.tsx
Quiz End throws an error, which need to be fixed and quiz view is broken also
> fix(frontend): fixed quiz view and end

- mobile/bulingo/app/(tabs)/index.tsx
- mobile/bulingo/app/Alert.ts
- mobile/bulingo/app/components/topNotification.tsx
- mobile/bulingo/app/login.tsx
- mobile/bulingo/app/register.tsx
Fixes #845.
This is simple bug fix PR. It makes it so that the notification displayed in the home page is communicated via a singleton class (Alert), and this fixes the issue with the notification popping up again whenever the user navigates to the home page.
> Home Page Always Shows Notification Fix

- frontend/src/components/common/navbar.tsx
- frontend/src/components/common/user-card.tsx
- frontend/src/components/common/utils.tsx
- frontend/src/components/post/post-card.tsx
- frontend/src/components/quiz/question-card.tsx
- frontend/src/components/quiz/quiz-card.tsx
- frontend/src/pages/profile-update.tsx
- frontend/src/pages/profile.tsx
- frontend/src/types.ts
[issue](https://github.com/bounswe/bounswe2024group6/issues/855)
> Frontend 855: implemented all profile image related features

- frontend/src/components/post/compose-post-form.tsx
- frontend/src/components/post/tag-search-modal.tsx
> feat(frontend): creating custom tags when creating post

- frontend/src/pages/forum.tsx
> feat(frontend): searchable custom tags in custom filtering

- frontend/src/components/auth/login.tsx
- frontend/src/components/auth/protect-routes.tsx
- frontend/src/components/auth/utils.tsx
- frontend/src/components/common/navbar.tsx
- frontend/src/pages/profile.tsx
> feat(frontend): keep role in cookies and implement isAdmin hook

- frontend/src/components/post/compose-post-form.tsx
- frontend/src/pages/profile.tsx
[issue](https://github.com/bounswe/bounswe2024group6/issues/819)
> feat(frontend): added liked posts and comments to profile

- frontend/src/components/admin/ban-user-modal.tsx
- frontend/src/pages/profile.tsx
> feat(frontend): implement admin ban user functionality

- backend/app/serializers.py
> feat(backend): is_banned field on profile endpoint

- backend/app/tests/integration/test_1_authentication_flow.py
- backend/app/tests/integration/test_2_authentication_and_profile_flow.py
- backend/app/tests/unit/test_1_authentication_views.py
- backend/app/tests/unit/test_2_profile_views.py
- backend/app/tests/unit/test_3_post_views.py
- backend/app/tests/unit/test_4_comments.py
- backend/app/tests/unit/test_5_comment_bookmarks.py
- backend/app/tests/unit/test_6_feed_views.py
- backend/app/tests/unit/test_7_follow_unfollow.py
tests refactoring, 54 tests are rewritten from scratch including new tests.
> Backend 864

- frontend/src/components/common/utils.tsx
- frontend/src/pages/profile.tsx
- frontend/src/types.ts
> feat(frontend): show is_banned information on profile

- frontend/src/pages/profile.tsx
> feat(frontend): show bookmarked comments in profile

- mobile/bulingo/app/(tabs)/forums/forumPostPage.tsx
- mobile/bulingo/app/(tabs)/quizzes/quizDetails.tsx
- mobile/bulingo/app/(tabs)/quizzes/quizQuestion.tsx
- mobile/bulingo/app/(tabs)/quizzes/quizResults.tsx
- mobile/bulingo/app/(tabs)/quizzes/quizReview.tsx
- mobile/bulingo/app/api/forum.ts
- mobile/bulingo/app/components/commentcard.tsx
- mobile/bulingo/app/components/modalDictionary.tsx
- mobile/bulingo/app/components/postcard.tsx
- mobile/bulingo/app/components/quizCard.tsx
- mobile/bulingo/app/pressableText.tsx
Added word meaning search functionality to the following pages and components:
- forumpostpage
- quizdetails
- quizquestion
- quizresults
- quizreview
- postcard
- quizcard
> feat(mobile): Pressable Text addition to the texts across Forum and Quiz pages

- frontend/src/components/admin/delete-post-modal.tsx
- frontend/src/components/post/edit-post-form.tsx
- frontend/src/components/post/post-card.tsx
- frontend/src/main.tsx
- frontend/src/pages/edit-post.tsx
> feat(frontend): implement admin post/comment delete and modify tags functionality

- frontend/src/components/quiz/create-quiz-metadata.tsx
- frontend/src/components/quiz/quiz-card.tsx
- frontend/src/components/quiz/quiz-tag-search-modal.tsx
> feat(frontend): creating custom tags when creating quiz

- frontend/src/pages/quizzes.tsx
> feat(frontend): add searchable custom tags in quiz feed filtering

- frontend/src/pages/forum.tsx
- frontend/src/pages/quizzes.tsx
> fix(frontend): deduplicate tags in tag search autocomplete

- mobile/bulingo/app/(tabs)/forums/forumPostPage.tsx
- mobile/bulingo/app/api/forum.ts
- mobile/bulingo/app/components/commentcard.tsx
- Bookmark comment functionality is added.
> MOBILE: Bookmark Comment Functionality for Forum Post

- mobile/bulingo/app/(tabs)/forums/forumPostCreation.tsx
Now, we can add custom tags during post creation process.
> MOBILE: Add custom tags during post creation process

- mobile/bulingo/app/api/forum.ts
- mobile/bulingo/app/components/commentcard.tsx
- Added image to the Comment Card component to display the comments' authors.
> Show the comments' authors profile pictures in the Forum Post Page

- mobile/bulingo/app/components/commentcard.tsx
- User is redirected to comment author's profile page when the username is clicked in Forum Post Comments.
> MOBILE: Redirect the user to comment author's profile page when the username is clicked in Forum Post Comments.

- frontend/src/components/admin/delete-quiz-modal.tsx
- frontend/src/components/admin/edit-quiz-tags-modal.tsx
- frontend/src/components/quiz/create-quiz-metadata.tsx
- frontend/src/components/quiz/quiz-card.tsx
> feat(frontend): implement admin quiz delete and modify tags functionality

- frontend/src/components/common/navbar.tsx
- frontend/src/pages/post.tsx
> feat(frontend): complete activity stream notifications

- frontend/src/components/quiz/create-quiz-question.tsx
- frontend/src/pages/quiz-creation.tsx
- frontend/src/pages/quiz-review.tsx
- frontend/src/pages/quiz.tsx
- frontend/src/types.ts
Users should be able to either add pictures to their questions manually or generate pictures based on the word given.
> Frontend: Add Image Adding Functionality to Quiz Questions

- mobile/bulingo/app/(tabs)/forums/forumPostPage.tsx
- mobile/bulingo/app/(tabs)/forums/index.tsx
- mobile/bulingo/app/(tabs)/quizzes/index.tsx
- mobile/bulingo/app/(tabs)/quizzes/quizDetails.tsx
- mobile/bulingo/app/TokenManager.ts
- mobile/bulingo/app/api/forum.ts
- mobile/bulingo/app/components/commentcard.tsx
Forum and Quiz pages are now Guest/Authenticated user sensitive.
> MOBILE: 910 mobile add guest user restrictions to the forum and quiz pages

- backend/app/serializers.py
> impr: give author info on profile posts.

- backend/app/urls.py
- backend/app/views_directory/quiz_views.py
> feat: cancel quiz given quiz_id.

- frontend/src/components/quiz/quiz-details-skeleton.tsx
- frontend/src/pages/post.tsx
- frontend/src/pages/profile-update.tsx
- frontend/src/pages/profile.tsx
- frontend/src/pages/quiz-details.tsx
- frontend/src/pages/quiz.tsx
[issue](https://github.com/bounswe/bounswe2024group6/issues/926)
> Frontend 926: added skeletons to pages

- backend/app/serializers.py
> fix: pass context  to commentserializer in profile serializer.

- frontend/src/pages/quiz-details.tsx
- frontend/src/pages/quiz.tsx
- frontend/src/types.ts
removed quiz restart. only resume. endpoints are not usable.
> Frontend 924: implementation of resume/start

- frontend/src/components/post/post-card.tsx
- frontend/src/pages/forum.test.tsx
> feat(frontend): write guest and admin view unit tests

- frontend/src/components/post/compose-post-form.tsx
- frontend/src/pages/forumCompose.test.tsx
After adding customized tag selection feature to forum post compose page, unit tests need to be adjusted according to the new changes
> fix(frontend): post compose tests are fixed

- frontend/src/pages/post.tsx
[issue](https://github.com/bounswe/bounswe2024group6/issues/942)
> fix(frontend): made forum recursive AGAIN

- frontend/src/components/quiz/quiz-details-skeleton.tsx
- frontend/src/components/quiz/quiz-end-skeleton.tsx
- frontend/src/components/quiz/quiz-question-skeleton.tsx
- frontend/src/pages/quiz-end.tsx
- frontend/src/pages/quiz.tsx
Quiz skeletons need to be arranged in harmony with the original components
> fix(frontend): Added quiz related skeletons

- mobile/bulingo/app/(tabs)/notifications.tsx
- mobile/bulingo/app/(tabs)/search.tsx
- notification overflow issue is fixed
- when the post is clicked, the user is redirected to the post page.
> MOBILE: 951 mobile final fixes and checks before release

- frontend/src/components/common/utils.tsx
- frontend/src/pages/quiz-details.tsx
- frontend/src/types.ts
Currently, there is a default picture shown in quiz details page, it needs to be fetched according to the created quiz image
> fix(frontend): Displayed images on quiz details page

- mobile/bulingo/app/(tabs)/profile/userCard.tsx
- mobile/bulingo/app/components/commentcard.tsx
- mobile/bulingo/app/components/postcard.tsx
- mobile/bulingo/app/components/quizCard.tsx
- mobile/bulingo/app/components/tagEdit.tsx
Fixes #952.
This PR handles all of the admin connections. In particular,
* The correct alert is shown when an action is taken.
* The Comment Delete endpoint return 204, which throws an error. This error is now ignored and displayed as a warning.
* Post Tags are now editable
* Quiz Tags are now editable
> Admin Mobile-Backend Connection Fixes

- frontend/src/components/quiz/question-card.tsx
- frontend/src/pages/forum.tsx
- frontend/src/pages/post.tsx
- frontend/src/pages/quiz-details.tsx
- frontend/src/pages/quiz-end.tsx
some many issues in [here](https://github.com/bounswe/bounswe2024group6/issues/966)
> fix(frontend): fixed various things

- mobile/bulingo/app/(tabs)/forums/forumPostPage.tsx
- mobile/bulingo/app/(tabs)/forums/index.tsx
- mobile/bulingo/app/(tabs)/profile/bookmarkedPostsAndComments.tsx
- mobile/bulingo/app/(tabs)/profile/index.tsx
- mobile/bulingo/app/(tabs)/profile/likedPostsAndComments.tsx
- mobile/bulingo/app/(tabs)/profile/users/[username]/index.tsx
- mobile/bulingo/app/components/postcard.tsx
Fixes #965.
This is a simple PR showing the description in each forum card.
> Show Description in Forum Card

- mobile/bulingo/__tests__/commentcard.test.tsx
- mobile/bulingo/__tests__/postcard.test.tsx
- mobile/bulingo/__tests__/quizCard.test.tsx
- mobile/bulingo/__tests__/userCard.test.tsx
- mobile/bulingo/app/(tabs)/notifications.tsx
Fixes #982.
Most of the tests are fixed, only a single one doesn't pass now. 
Also, the notification page design has been updated to be two lines long with the time on the second line.
> Fix some Tests & Notification Page

- frontend/src/components/quiz/quiz-card.tsx
- frontend/src/pages/quiz-review.test.tsx
[issue](https://github.com/bounswe/bounswe2024group6/issues/984)
> feat(frontend): added quiz review test

- backend/app/tests/unit/test_10_quiz.py
> chore(backend): quiz tests.

- mobile/bulingo/__tests__/quizDetails.test.tsx
- mobile/bulingo/__tests__/quizReview.test.tsx
Fixes #987.
Added new unit test
> feat(mobile): add unit tests and remove old ones
