bounswe/bounswe2024group6

- .gitignore
- backend/django-rest-auth/server/utils.py
"Image" key of the response data will have a default value of "No Image" if there's no image property of the WikiData.
> fix: image key default value 

- mobile/searchitect/app/navbar.tsx
Fixes #351.
In this implementation, the buttons in the Navbar have their opacity reduced to 70% when they are pressed. We could indicate the button presses some other way if you have any other ideas (such as by changing the background color).
Also, the navbar.tsx file has been formatted for better readability, using the tool "https://codebeautify.org/react-formatter".
> MOBILE-351: Add Press Indicators to Navbar Buttons

- mobile/searchitect/app/navbar.tsx
This PR includes a small functional change to the Navbar component. It can be used in the same way as before, but now it also takes 4 optional arguments for the 4 buttons it has to enable extending its functionality. These optional functions are called before the Navbar performs its normal onPress functionality.
> feat(mobile): add extensible navbar buttons

- mobile/bulingo/app/(tabs)/_layout.tsx
- mobile/bulingo/app/(tabs)/profile/userCard.tsx
- mobile/bulingo/app/(tabs)/search.tsx
- mobile/bulingo/app/components/quizCard.tsx
Fixes #465
This PR includes the designs for the search page. This search page is designed to be a general search for the app, showing search results for users, quizzes and forums. This is up-for-debate though, as we already have search functionality in the Quiz and Forum pages separately. Still, having a general place for searching may be nice.
I have also added sorting and filtering options. You can sort by newest or most liked, and you can use the filters to constrain the search to certain content types and tags. The search functionality was left entirely to the backend. I have integrated the page's design with quizCard and userCard components, but forum post and comment cards have not been merged to main yet and therefore they have placeholders instead. You can find example screenshot …
> feat(mobile): Search Page

- mobile/bulingo/app/login.tsx
- mobile/bulingo/app/register.tsx
Fixes #463.
- Login page is redesigned. 
- Register page is redesigned. 
- Home page is moved to the new tabs section.
> refactor(mobile): redesign login and register pages 

- mobile/bulingo/app/login.tsx
- mobile/bulingo/app/register.tsx
Fixes #569.
- The navigation bar has been removed from the Login and Register pages.
- The style of the "Log In" text has been changed to align with the "Register" text.
- The Register button on the Log In page has been enabled.
- A Return Home button has been added to the Register page.
> refactor(mobile): Remove Navigation Bar from Login and Register Pages

- mobile/bulingo/app/(tabs)/quizzes/quizCreationSettings.tsx
Fixes #563.
- Unique key error on Quiz Creation Settings Page is fixed.
> fix(mobile): fix unique key error on Quiz Creation Settings

- mobile/bulingo/app/(tabs)/profile/userCard.test.tsx
- mobile/bulingo/app/(tabs)/profile/userCard.tsx
- mobile/bulingo/app/components/commentcard.test.tsx
- mobile/bulingo/app/components/commentcard.tsx
- mobile/bulingo/app/components/postcard.test.tsx
- mobile/bulingo/app/components/postcard.tsx
- mobile/bulingo/app/components/quizCard.test.tsx
- mobile/bulingo/app/components/quizCard.tsx
- mobile/bulingo/package-lock.json
- mobile/bulingo/package.json
Fixes #586
This PR includes unit tests for userCard, commentcard, postcard and quizCard components. The unit tests cover the various buttons and the texts that should be present on the screen. 
This PR also includes slight changes to the components it is testing, but these should have no behavioral or visual effect, it just adds testID props to some components.
For testing, jest was used.
> test(mobile: add unit tests for card components

- mobile/bulingo/__tests__/commentcard.test.tsx
- mobile/bulingo/__tests__/postcard.test.tsx
- mobile/bulingo/__tests__/quizCard.test.tsx
- mobile/bulingo/__tests__/userCard.test.tsx
Fixes #668.
This PR includes the most straight-forward solution to the error we were encountering. When the tests were included in the app folder, they were always being viewed as different components and they always lead to errors. This PR moves the tests to a new '\_\_tests__' directory. The tests all pass (you can try with `npm test`), and the code works successfully without throwing errors at the start.
I have tried many other methods to fix this issue, such as changing jest config, installing new react versions or new libraries, but this is the only one that worked.
> fix(mobile): fix reference error in tests

- mobile/bulingo/app/(tabs)/index.tsx
- mobile/bulingo/app/(tabs)/notifications.tsx
- mobile/bulingo/app/(tabs)/profile/bookmarkedPostsAndComments.tsx
- mobile/bulingo/app/(tabs)/profile/bookmarkedQuizzes.tsx
- mobile/bulingo/app/(tabs)/profile/editProfile.tsx
- mobile/bulingo/app/(tabs)/profile/followers.tsx
- mobile/bulingo/app/(tabs)/profile/following.tsx
- mobile/bulingo/app/(tabs)/profile/index.tsx
- mobile/bulingo/app/(tabs)/profile/likedQuizzes.tsx
- mobile/bulingo/app/(tabs)/profile/userCard.tsx
- mobile/bulingo/app/(tabs)/profile/users/[username].tsx
- mobile/bulingo/app/(tabs)/profile/users/[username]/followers.tsx
- mobile/bulingo/app/(tabs)/profile/users/[username]/following.tsx
- mobile/bulingo/app/(tabs)/profile/users/[username]/index.tsx
- mobile/bulingo/app/(tabs)/quizzes/index.tsx
- mobile/bulingo/app/TokenManager.ts
- mobile/bulingo/app/components/topNotification.tsx
- mobile/bulingo/app/login.tsx
- mobile/bulingo/app/register.tsx
- mobile/bulingo/package-lock.json
Fixes #648
This PR includes the changes from #654, and therefore SHOULD NOT BE MERGED BEFORE PR #654 IS MERGED!
The solution I came up with is relatively simple, instead of finding every single point where something related to the profile changes, I refresh the profile page whenever it is navigated to so it always has the latest data. This is a slower approach but it is more precise and error-proof.
> fix(mobile): Refresh profile page dynamically

- mobile/bulingo/__tests__/userCard.test.tsx
Fixes #685.
This is a simple PR that just changes the test. The test was broken because the userCard component now makes an authenticated network request which results in two problems:
1- The authenticatedFetch function has to be mocked
2- Since the button now calls an async function, we need to add a small delay before we check if the function has been called.
> fix(mobile): fix the broken userCard test

- mobile/bulingo/app/(tabs)/profile/index.tsx
Fixes #676.
This PR includes a small change to the profile/index.tsx page. It gets rid of the warnings found in the page that are caused by  the debugUserInfo object. The comment and post handling/displaying is not perfect in this PR, but it is not the focus. It will be fixed once the forum is successfully connected to backend.
> fix(mobile): remove debugUserInfo from profile/index

- mobile/bulingo/__tests__/quizReview.test.tsx
- mobile/bulingo/app/(tabs)/quizzes/quizReview.tsx
Fixes #682.
- Add unit tests for the quiz review page.
- Verify that the texts are displayed correctly.
- Ensure that the wrong answer and correct answer buttons have the appropriate colors.
- Test that the "Next" and "Previous" buttons work as expected.
- Confirm that API errors are handled gracefully.
- Add timer for animations and wrap wrap state-changing events with act.
> feat(mobile): add unit tests for quiz review page

- backend/app/views_directory/comments.py
Fixes #794
This is an extremely simple PR, just removing the check for the author being the DELETE request sender when an admin tries to delete the comments of anyone.
> Let admins delete comments of everyone (BACKEND)

- mobile/bulingo/app/components/modalDictionary.tsx
Fixes #832.
This is a really simple bug fix PR. The change is that now, the ModalDictionary component fetches the bookmarked words of the currently logged in user and checks if the currently displayed word is among them to change the look and function of the bookmark button.
> Fix ModalDictionary not displaying Bookmark info correctly (Mobile)

- mobile/bulingo/app/(tabs)/search.tsx
Fixes #867.
This PR addresses the known bug where the UserCard component would not display the profile picture of a user when viewed in the search page. It is a really simple PR, you can test it by searching for the user 'ygz' in the search page.
> Show Profile Pictures in the Search Page (Mobile)

- mobile/bulingo/app/(tabs)/quizzes/quizCreationInfo.tsx
Fixes #872. 
- Added the API connection to the mobile app.
- Extracted wrong answers and formatted them for display in the quiz creation UI.
- Implemented error messages for cases where the endpoint fails or provides incomplete data.
- Tested the implemented functionality on an emulated android device.
- There exists a problem with backend, results are meaningless but I cannot fix the problem on mobile since it is irrelevant. I've already reported to the issue to the backend team.
> feat(mobile): Provide Wrong Answers on Quiz Creation

- mobile/bulingo/app/(tabs)/notifications.tsx
- mobile/bulingo/app/(tabs)/profile/index.tsx
- mobile/bulingo/app/(tabs)/profile/userCard.tsx
- mobile/bulingo/app/(tabs)/search.tsx
- mobile/bulingo/app/TokenManager.ts
- mobile/bulingo/app/components/commentcard.tsx
- mobile/bulingo/app/components/guestModal.tsx
- mobile/bulingo/app/components/postcard.tsx
- mobile/bulingo/app/components/quizCard.tsx
Fixes #848.
This PR implements the functionality needed for guests in the Notifications, Profile and Search tabs. The main changes are the following:
* A new guest modal has been created that prompts the user to either login or register. This component is reused in many pages. Whenever a guest tries to do something that they can't, they are shown this modal.
* The guests can't access the Profile tab.
* The guests can't access the Notifications tab.
* The guests can't press the like / bookmark button in the QuizCard.
* The guests can't press the like / bookmark button in the PostCard.
* The guests can't press the follow / unfollow buttons or the user card itself.
* The guests can't press the like / bookmark buttons in the CommentCard.
* Search is now usable by guests.
> Guest Views for Notifications, Profile, and Search Pages & Components (Mobile)

- mobile/bulingo/app/(tabs)/index.tsx
- mobile/bulingo/app/(tabs)/notifications.tsx
- mobile/bulingo/app/(tabs)/profile/userCard.tsx
- mobile/bulingo/app/(tabs)/search.tsx
- mobile/bulingo/app/TokenManager.ts
- mobile/bulingo/app/components/adminOptions.tsx
- mobile/bulingo/app/components/commentcard.tsx
- mobile/bulingo/app/components/postcard.tsx
- mobile/bulingo/app/components/quizCard.tsx
- mobile/bulingo/app/components/tagEdit.tsx
- mobile/bulingo/app/login.tsx
Fixes #853. Fixes #737.
This is a huge PR that includes a lot of really important changes. You can look at the individual commit messages for more information. To give you a general overview, the following are the main problems addressed in this PR:
* Add an admin modal component that shows up if an admin presses and holds some components
* Give the option to ban a user after pressing their user card
* Give the option to change the tags of a quiz after pressing the quiz card
* Give the option to delete a quiz after pressing the quiz card
* Give the options to delete/change tags of post after pressing the post card
* Give the option to delete a comment after pressing the comment card
* Correctly check if a user is an admin when they log in.
* Update notifications with new messages.
* …
> Mobile Notifications & Admin Pages

- mobile/bulingo/app/(tabs)/quizzes/quizCreationInfo.tsx
- mobile/bulingo/app/(tabs)/quizzes/quizCreationQuestionList.tsx
Fixes #892.
- This PR enables users to upload images for quiz questions.
- Deleting and changing image is possible. 
- The image is stored persistently until quiz is submitted. (Question list page keeps the images until quiz is submitted which allows users to edit images later on question update)
-  The utility is tested on an emulated android device. 
Example Image:
> feat(mobile): enable image upload on quiz creation

- mobile/bulingo/app/(tabs)/quizzes/quizQuestion.tsx
- mobile/bulingo/app/(tabs)/quizzes/quizReview.tsx
Fixes #917.
- The quiz image is now enabled on both the quiz question page and the quiz review page.
- If a quiz image is available, it is displayed alongside the quiz question text.
- If no quiz image is found, only the quiz question text is displayed.
Here are example images:
> feat(mobile): display quiz images on mobile

- mobile/bulingo/app/pressableText.tsx
Fixes #928.
Extremely small fix that just adds an onPress optional prop to the pressable text component.
> Add onPress to pressable text

- mobile/bulingo/app/(tabs)/quizzes/quizCreationInfo.tsx
Fixes #938.
- Set LocalImage to null and removed encoding when the image is undefined. This ensures the functionality works as intended.
- Verified the fix on an emulated Android device.
> fix(mobile): Fix the problem with Image display on quiz question update 

- mobile/bulingo/app/(tabs)/quizzes/quizQuestion.tsx
- mobile/bulingo/app/(tabs)/quizzes/quizReview.tsx
Fixed #933.
- Made quiz options on the quiz question and quiz review pages horizontally scrollable.
- This PR resolves the issue of lengthy quiz answers affecting the UI layout. 
- Tested on an emulated android device.
> feat(mobile): make quiz options scrollable

- mobile/bulingo/app/(tabs)/profile/bookmarkedPostsAndComments.tsx
- mobile/bulingo/app/(tabs)/profile/bookmarkedQuizzes.tsx
- mobile/bulingo/app/(tabs)/profile/index.tsx
- mobile/bulingo/app/(tabs)/profile/likedPostsAndComments.tsx
- mobile/bulingo/app/(tabs)/profile/users/[username]/index.tsx
- mobile/bulingo/app/TokenManager.ts
- mobile/bulingo/app/_layout.tsx
Fixes #921.
This PR includes changes to a variety of pages in the profile. The complete list of changes can be found below.
* The placeholders in the Profile tab have been replaced with 'card' components.
* The bookmarked and liked posts/comments pages have been connected to the backend
* The postcard and commentcard components used in these pages have been made operational, with functional like and bookmark buttons.
> Profile Page Fixes for PostCard and CommentCard pages

- mobile/bulingo/app/components/quizCard.tsx
Fixes #961.
This is a small feature that shows the quiz level/tags on the bottom of the QuizCard components. They use the same style as the old level tag.
> Show Quiz Tags on Mobile

- mobile/bulingo/app/(tabs)/quizzes/quizDetails.tsx
Fixes #969.
- Add quiz card to the quiz details page.
Example Image:
> feat(mobile): add quiz card on quiz details page
